CLASS_NAMES: ['Building', 'Fully_loaded_cargo_ship', 'Fully_loaded_container_ship', 'Lock_gate', 'Tree', 'Unladen_cargo_ship']

DATA_CONFIG: 
    _BASE_CONFIG_: cfgs/dataset_configs/trout_dataset.yaml
    POINT_CLOUD_RANGE: [0.0, 0.0, -5.12, 102.4, 102.4, 5.12]
    DATA_PROCESSOR:
        - NAME: mask_points_and_boxes_outside_range
          REMOVE_OUTSIDE_BOXES: True

        - NAME: shuffle_points
          SHUFFLE_ENABLED: {
            'train': True,
            'val': False,
            'test': False
          }

        - NAME: transform_points_to_voxels
          VOXEL_SIZE: [0.128, 0.128, 10.24]
          MAX_POINTS_PER_VOXEL: 32
          MAX_NUMBER_OF_VOXELS: {
            'train': 160000,
            'test': 160000
          }
    DATA_AUGMENTOR:
        DISABLE_AUG_LIST: ['placeholder']
        AUG_CONFIG_LIST:
            - NAME: gt_sampling
              USE_ROAD_PLANE: False
              DB_INFO_PATH:
                  - TROUT_dbinfos_train.pkl
              PREPARE: {
                 filter_by_min_points: ['Building:5', 'Fully_loaded_cargo_ship:5', 'Fully_loaded_container_ship:5', 'Lock_gate:5', 'Tree:5', 'Unladen_cargo_ship:5'],
                 #filter_by_difficulty: [-1],
              }

              SAMPLE_GROUPS: ['Building:15', 'Fully_loaded_cargo_ship:15', 'Fully_loaded_container_ship:15', 'Lock_gate:15', 'Tree:15', 'Unladen_cargo_ship:15']
              NUM_POINT_FEATURES: 4
              DATABASE_WITH_FAKELIDAR: False
              REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
              LIMIT_WHOLE_SCENE: True

MODEL:
    NAME: PointPillar

    VFE:
        NAME: PillarVFE
        WITH_DISTANCE: False
        USE_ABSLOTE_XYZ: True
        USE_NORM: True
        NUM_FILTERS: [64]

    MAP_TO_BEV:
        NAME: PointPillarScatter
        NUM_BEV_FEATURES: 64

    BACKBONE_2D:
        NAME: BaseBEVBackbone
        LAYER_NUMS: [3, 5, 5]
        LAYER_STRIDES: [2, 2, 2]
        NUM_FILTERS: [64, 128, 256]
        UPSAMPLE_STRIDES: [1, 2, 4]
        NUM_UPSAMPLE_FILTERS: [128, 128, 128]

    DENSE_HEAD:
        NAME: AnchorHeadSingle
        CLASS_AGNOSTIC: False

        USE_DIRECTION_CLASSIFIER: True
        DIR_OFFSET: 0.0
        DIR_LIMIT_OFFSET: 0.0
        NUM_DIR_BINS: 2

        ANCHOR_GENERATOR_CONFIG: [
            {
                'class_name': 'Building',
                'anchor_sizes': [[13.7, 9.5, 4.0]],
                'anchor_rotations': [-1.57, 1.57],
                'anchor_bottom_heights': [-0.1],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.8,
                'unmatched_threshold': 0.5
            },
            {
                'class_name': 'Fully_loaded_cargo_ship',
                'anchor_sizes': [[44.6, 10.5, 4.5]],
                'anchor_rotations': [-1.57, 1.57],
                'anchor_bottom_heights': [-4.2],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.8,
                'unmatched_threshold': 0.5
            },
            {
                'class_name': 'Fully_loaded_container_ship',
                'anchor_sizes': [[46.76, 10.6, 6.4]],
                'anchor_rotations': [-1.57, 1.57],
                'anchor_bottom_heights': [-4.2],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.8,
                'unmatched_threshold': 0.5
            },
            {
                'class_name': 'Lock_gate',
                'anchor_sizes': [[3.9, 23.0, 3.7]],
                'anchor_rotations': [-1.57, 1.57],
                'anchor_bottom_heights': [-4.2],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.8,
                'unmatched_threshold': 0.5
            },
            {
                'class_name': 'Tree',
                'anchor_sizes': [[56.6, 17.5, 3.8]],
                'anchor_rotations': [-1.57, 1.57],
                'anchor_bottom_heights': [-0.1],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.8,
                'unmatched_threshold': 0.5
            },
            {
                'class_name': 'Unladen_cargo_ship',
                'anchor_sizes': [[45.76, 14.0, 6.8]],
                'anchor_rotations': [-1.57, 1.57],
                'anchor_bottom_heights': [-4.2],
                'align_center': False,
                'feature_map_stride': 2,
                'matched_threshold': 0.8,
                'unmatched_threshold': 0.5
            }
        ]


        TARGET_ASSIGNER_CONFIG:
            NAME: AxisAlignedTargetAssigner
            POS_FRACTION: -1.0
            SAMPLE_SIZE: 512
            NORM_BY_NUM_EXAMPLES: False
            MATCH_HEIGHT: False
            BOX_CODER: ResidualCoder

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 2.0,
                'dir_weight': 0.2,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: trout

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.01
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500


OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 2
    NUM_EPOCHS: 80

    OPTIMIZER: adam_onecycle
    LR: 0.003
    WEIGHT_DECAY: 0.01
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10
